### PR TITLE
Pulido/issue89

### PR DESCRIPTION
**Pull request by jpulidojr**
Moved examples around, added datasync example, and updated terminology to include readers/writers, and backends.

### CODE REVIEW

**Comment by terryturton** [comment]
@jpulidojr - should docs/drivers/generate_driver_class_hierarchy.py be renamed/removed?

**Comment by jpulidojr** [comment]
I had not touched portions of the docs, I will update it

**Review by hugegreenbug — APPROVED** [review]
Passed the PENNANT example test

**Review by terryturton — APPROVED** [review]
Thanks for the updates, approved.

**Pull request merged**
