### PR TITLE
Bueno plugin: handle multiple files

### PR DESCRIPTION
**Pull request by qwofford**
taking advantage of some of Daniel's work on new plugin types for files

### CODE REVIEW

**Comment by qwofford** [comment]
@DanielRJohnson Can you take a look at this PR and take a shot at the sampling problem described in the most recent commit message. This is the highest priority DSI issue at the moment and I'm down an arm...let me know if you have questions about how it should work.

**Comment by DanielRJohnson** [comment]
@qwofford Of course, take it easy!

**Comment by DanielRJohnson** [comment]
The reason that it was overwriting was that pack_header was being called every add_rows call, which initializes every column to an empty list.

**Comment by DanielRJohnson** [comment]
Tests and pylama pass, ready to merge I think

**Review by DanielRJohnson — APPROVED** [review]

**Pull request merged**
