### PR TITLE
Make a SQlite driver that operates on one of DSI's queriable middleware data structures.

### LINKED ISSUE #77: Core: Problems with loadingh multiple back-end drivers
1. Load a Csv (or other) plugin.
2. Load both Parquet and SQLite back-end drivers.
4. Call transload operation to pull.
5. Gives type error "unexpected object 'collection' not found"

### PR DESCRIPTION
**Pull request by qwofford**
Resolves #77.

I recommend adding unit tests that catch any failure modes not currently represented. see `dsi/drivers/tests/*` for existing examples.

### CODE REVIEW

**Comment by qwofford** [comment]
this should be ready to go.

**Comment by qwofford** [comment]
Note that we should squash these commits because I made a mess of the git history while resolving conflicts.

**Comment by jpulidojr** [comment]
Reviewed and pass CI. I will be using this in the near future and if I find anything I will open another issue.

**Review by jpulidojr — APPROVED** [review]
Reviewed and pass CI. I will be using this in the near future and if I find anything I will open another issue.

**Pull request merged**
