### PR TITLE
Add parquet unit tests. Add static html generator output for parquet front end.

### LINKED ISSUE #81: Make default Parquet inspect_artifact method non-interactive.
Instead of generating a notebook and opening it interactively, generate the jupyter notebook and also a static html output of the same content. The sure can will use an optional inspect_artifacts parameter to generate, execute, and then open the notebook interactively without generating a static html page.

### PR DESCRIPTION
**Pull request by qwofford**
Resolves #81 and #82.

### CODE REVIEW

**Comment by qwofford** [comment]
Also closes #85 .

Note that my set of software requirments is generated from `conda list --export`, and it is more verbose than we likely need. If this causes issues we should remove the offending lines. It works for me on multiple platforms and OS distributions, so I'm inclined to leave it as it is in this PR unless someone else has problems.

requirements.txt can be freely modified now or in the future. It is meant as a convenience.

**Comment by qwofford** [comment]
Also resolves #86

**Review by jpulidojr — COMMENTED** [review]
I reviewed the sqlite changes and this works. 

My only concern is that the requirements.txt seems to be parquet specific and not DSI. do we want to withhold these? Otherwise we are significantly increasing the number of dependencies for the base DSI code.

**Review by jpulidojr — APPROVED** [review]
Issue 89 will address the requirements.txt as a per-example addition to the code

**Pull request merged**
