### PR TITLE
Improve software packaging, incorporate sphinx documentation creation workflow

### PR DESCRIPTION
**Pull request by qwofford**
Can I get someone to test the documentation generator in `./docs` before approving please.

### CODE REVIEW

**Comment by cmahrens** [comment]
I built and checked the pages and they look fine.

**Review by hugegreenbug — COMMENTED** [review]
The docs built fine. I got the following warnings:

```
WARNING: autodoc: failed to import module 'sql.fs.fs' from module 'dsi'; the following exception was raised:
No module named 'dsi'
WARNING: autodoc: failed to import module 'utils.utils' from module 'dsi'; the following exception was raised:
No module named 'dsi'
```

I fixed this by adding this to conf.py:

```
import os, sys
sys.path.insert(0, os.path.abspath('../'))
```

**Comment by cmahrens** [comment]
I got that too, but not after setting my PYTHONPATH.  I did mention that I had to set my PYTHONPATH to Quincy but I thought he didn't feel that warranted a change in the instructions and was implied.


Christine


-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________
From: Hugh Greenberg ***@***.***>
Sent: Wednesday, June 7, 2023 9:29 AM
To: lanl/dsi
Cc: Sweeney, Christine Marie; State change
Subject: [EXTERNAL] Re: [lanl/dsi] Improve software packaging, incorporate sphinx documentation creation workflow (PR #10)


@hugegreenbug commented on this pull request.

The docs built fine. I got the following warnings:

WARNING: autodoc: failed to import module 'sql.fs.fs' from module 'dsi'; the following exception was raised:
No module named 'dsi'
WARNING: autodoc: failed to import module 'utils.utils' from module 'dsi'; the following exception was raised:
No module named 'dsi'


I fixed this by adding this to conf.py<https://urldefense.com/v3/__http://conf.py__;!!Bt8fGhp8LhKGRg!AoDfvki8Q-kt5zYziFFNMTe4dpbhTG_RC0oetIHRMmD6zWv8rvIuttdtMXOdNvk3uCyPTd5LmhgTR2KjkoChazbf$>:

import os, sys
sys.path.insert(0, os.path.abspath('../'))

**Comment by qwofford** [comment]
Let's see if we can resolve this before it gets merged in. I don't want users to have to change their path. If dsi is installed correctly in the Python environment, it shouldn't give that error. @DanielRJohnson can you please take a look and make a PR into this branch if you have the same error?

**Comment by cmahrens** [comment]
But it makes sense that you would need to set your PYTHONPATH, because sphinx goes to the python to create the docs.  I just set the PYTHONPATH to add the dsi directory.


Christine


-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________
From: Quincy Wofford ***@***.***>
Sent: Wednesday, June 7, 2023 10:13 AM
To: lanl/dsi
Cc: Sweeney, Christine Marie; State change
Subject: [EXTERNAL] Re: [lanl/dsi] Improve software packaging, incorporate sphinx documentation creation workflow (PR #10)


Let's see if we can resolve this before it gets merged in. I don't want users to have to change their path. If dsi is installed correctly in the Python environment, it shouldn't give that error. @DanielRJohnson<https://urldefense.com/v3/__https://github.com/DanielRJohnson__;!!Bt8fGhp8LhKGRg!H-JhE-2PaJgGV1kiI_T4UT5CkTj-aTI_r9YjgS7aX459CqlCKt7ajYajmrfOGD6dgKms6veEHDGa_mduMQQtsAZr$> can you please take a look and make a PR into this branch if you have the same error?

**Comment by cmahrens** [comment]
I didn't "install dsi" first.  I just went to the docs directory and started there.


Christine


-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________
From: Quincy Wofford ***@***.***>
Sent: Wednesday, June 7, 2023 10:13 AM
To: lanl/dsi
Cc: Sweeney, Christine Marie; State change
Subject: [EXTERNAL] Re: [lanl/dsi] Improve software packaging, incorporate sphinx documentation creation workflow (PR #10)


Let's see if we can resolve this before it gets merged in. I don't want users to have to change their path. If dsi is installed correctly in the Python environment, it shouldn't give that error. @DanielRJohnson<https://urldefense.com/v3/__https://github.com/DanielRJohnson__;!!Bt8fGhp8LhKGRg!H-JhE-2PaJgGV1kiI_T4UT5CkTj-aTI_r9YjgS7aX459CqlCKt7ajYajmrfOGD6dgKms6veEHDGa_mduMQQtsAZr$> can you please take a look and make a PR into this branch if you have the same error?

**Comment by cmahrens** [comment]
I think the instructions on how to install dsi need to be updated because they refer to setup.py, which is not in your branch.


Christine


-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________

**Comment by cmahrens** [comment]
Yes, sorry, I did that step previously.


I get this for the dsi install after the sphinx stuff was installed.


...

Building wheels for collected packages: UNKNOWN
  Building wheel for UNKNOWN (pyproject.toml) ... done
  Created wheel for UNKNOWN: filename=UNKNOWN-0.0.0-py3-none-any.whl size=961 sha256=c29f4f044e26c31a6e0e994a2ad48cd118374fca44e26123e3c76e7ccd46941b
  Stored in directory: /ram/tmp/pip-ephem-wheel-cache-tx0bfhjr/wheels/35/3f/75/99551d4bb093025feb73e5866d11de0302c07b621cfc451ac1
Successfully built UNKNOWN
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
Successfully installed UNKNOWN-0.0.0
(env) ***@***.*** dsi]$

Maybe something wrong with the install bc it should be called dsi package?

What I meant in my previous comment is that the dsi/README.rst needs updating to not mention setup.py.

Christine


-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________
From: Quincy Wofford ***@***.***>
Sent: Wednesday, June 7, 2023 11:49 AM
To: lanl/dsi
Cc: Sweeney, Christine Marie; State change
Subject: [EXTERNAL] Re: [lanl/dsi] Improve software packaging, incorporate sphinx documentation creation workflow (PR #10)


Installing DSI for the purpose of publishing user-facing documentation is documented in docs/README.rstin "How to build documentation" section 3:

python -m pip install sphinx sphinx_rtd_theme .


The last "." argument is what says to look for pyproject.toml in the current directory. That's a required step to build docs successfully

**Comment by cmahrens** [comment]
@hugegreenbug were you also using virtualenv or using conda?

**Comment by qwofford** [comment]
Actually @cmahrens you found another bug in my pyproject.toml file. I'm glad virtualenv caught it. 

I had created a section in pyproject called "[dsi]", but the correct syntax is to use "[project]" in the section with a key-val in that section called "name=dsi". I fixed this and tested on my end.

Correcting this incorrectly named section also caught some errors in the pyproject.toml [project], which are also fixed.

Can you test again with virtualenv?

**Comment by cmahrens** [comment]
I did just test again with virtualenv but it didn't work -- same problem with the pip install of dsi.


I followed the directions for creating virtualenv from the darwin wiki.


curl https://bootstrap.pypa.io/pip/3.6/get-pip.py -o get-pip.py
python3 get-pip.py --user
which pip
export PATH=${PATH}:/vast/home/cahrens/.local/bin
pip install --user virtualenv
virtualenv env2
source env2/bin/activate
python3 -m pip install --upgrade pip
cd dsi
python -m pip install sphinx sphinx_rtd_theme .

I am only getting python 3.6.8 in the virtualenv.  Not sure how to get a newer version there.

Christine



-------------------------------------------
Christine Sweeney
5/40 schedule
(505) 551-2367 LANL cell
(505) 606-0195 LANL office
Programming Models Team Deputy Team Leader
Applied Computer Science (CCS-7)
Los Alamos National Laboratory

**Please don't feel obligated to respond to this
email outside of your regular work hours.**


________________________________
From: Quincy Wofford ***@***.***>
Sent: Wednesday, June 7, 2023 2:57 PM
To: lanl/dsi
Cc: Sweeney, Christine Marie; Mention
Subject: [EXTERNAL] Re: [lanl/dsi] Improve software packaging, incorporate sphinx documentation creation workflow (PR #10)


Actually @cmahrens<https://urldefense.com/v3/__https://github.com/cmahrens__;!!Bt8fGhp8LhKGRg!G0wQYOithG7Ck4u42VWVzPGMbpBJ5Vb7Fk6m67eBpW50JkoxEEJkaq6_pS0bJB080m5_Vvi_AaSx-WqgbBxNBf5Q$> you found another bug in my pyproject.toml file. I'm glad virtualenv caught it.

I had created a section in pyproject called "[dsi]", but the correct syntax is to use "[project]" in the section with a key-val in that section called "name=dsi". I fixed this and tested on my end.

Correcting this incorrectly named section also caught some errors in the pyproject.toml [project], which are also fixed.

Can you test again with virtualenv?

**Comment by qwofford** [comment]
I've been wrestling a bit with the pypa distributions of python, which aren't distributed beyond Python 3.7. I've included a note in the README.rst that says we suggest Miniconda for managing virtual environments. 

Perhaps if the Miniconda steps work for you, this could be sufficient?

**Comment by cmahrens** [comment]
I went back and created a virtualenv using python 3.11.  This built the html fine and I checked the pages were fine.  So, the problem must have been too out-of-date python (3.6) not doing what it should with the setuptools, perhaps.

I had to build the virtualenv with argument -p to point to the Python 3.11 binary that was pulled in when I made a conda environment during a previous attempt to build html.  virtualenv needs you to have a python installation of the version you want -- it doesn't pull it down for you.  At least that is what I am seeing in the documentation.

I think this PR has been beaten to death and as long as we say we tested it with or recommend python 3.11 conda and virtualenv, that should cover it.

**Review by cmahrens — APPROVED** [review]
I was able to build html with conda and virtualenv using Python 3.11.3 and pages look fine.  Documentation says it recommends Python 3.11, so that is good.

**Comment by qwofford** [comment]
Thanks very much for all of your help testing @cmahrens

**Pull request merged**
